# Generated by Django 6.1.1 on 2026-09-07 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=100, verbose_name='Название валюты')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Курс к USD')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10, verbose_name='Из валюты')),
                ('to_currency', models.CharField(max_length=10, verbose_name='В валюту')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('result', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата конвертации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История конвертации',
                'verbose_name_plural': 'История конвертаций',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoritePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10, verbose_name='Из валюты')),
                ('to_currency', models.CharField(max_length=10, verbose_name='В валюту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_pairs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранная пара',
                'verbose_name_plural': 'Избранные пары',
                'unique_together': {('user', 'from_currency', 'to_currency')},
            },
        ),
    ]
